CREATE TABLE IF NOT EXISTS orders(
id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
status_id INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (status_id) REFERENCES statuses(id) ON UPDATE CASCADE ON DELETE RESTRICT
);